### ISSUE TITLE
Blog entries don't show dates, blog listing does.

### ISSUE THREAD

**Issue by almereyda** [comunica/website#19]
When reading through the latest and previous release announcements, it has come to my attention that the blog entries do not display their date information, while the blog listing does. This is particularly irritating when looking at Changelogs, whose actuality depends on their date.

See this:

https://comunica.dev/blog/

![Screenshot 2021-08-30 at 20-14-43 Comunica – Blog](https://user-images.githubusercontent.com/1645308/131385436-30e9f0db-21a8-4769-87a2-2bae1cb3fcd0.png)

![Screenshot 2021-08-30 at 20-15-13 Comunica – Blog](https://user-images.githubusercontent.com/1645308/131385452-4c83724a-0c6f-45c2-8e14-6ae199f53005.png)

And that:

https://comunica.dev/blog/2021-08-30-release_1_22/

![Screenshot 2021-08-30 at 20-14-54 Comunica – Release 1 22 0 Improved update support, extension functions, and improved CLI ](https://user-images.githubusercontent.com/1645308/131385461-6d47ff88-2a9c-4074-8436-9d072f0b0bf4.png)

And the other:

https://comunica.dev/blog/2021-04-27-release_1_21/

![Screenshot 2021-08-30 at 20-15-22 Comunica – Release 1 21 0 Hypermedia-based SPARQL Updating](https://user-images.githubusercontent.com/1645308/131385484-1a11e173-bf20-4d30-8b2a-b2c6a19e2b0c.png)

**Comment by rubensworks** [comment]
Sure, should be easy to add.

**Comment by almereyda** [comment]
Thank you! I didn't know where to put this, but you did.
