### ISSUE TITLE
Blog RSS feed seemingly broken

### ISSUE THREAD

**Issue by ChewingBever** [comunica/website#21]
Hi, when I tried subscribing to the RSS feed of the blog, I noticed that it seems to be broken.

The `<header>` tag advertises the absolute URL `/rss-feed.xml` as the RSS feed. This does indeed return a valid xml file, but the post URLs are wrong. All post URLs are of the form `https://comunica.dev/blogpages/blog/2020-08-19-intro.md`. This URL is invalid because all posts URLs are now of the form `https://comunica.dev/blog/2021-11-08-comunica_association_members/`. My guess is that the RSS feed format might not have been updated to reflect the new blog's struct.

Here's an example of one of the `<item>` tags in the feed:
```
<item>
<title>
Release 1.16.0: Full spec compliance, property paths, CSV/TSV, basic auth, and fixes
</title>
<link>
https://comunica.dev/blogpages/blog/2020-08-24-release_1_16.md
</link>
<guid isPermaLink="false">pages/blog/2020-08-24-release_1_16.md</guid>
<pubDate>Thu, 24 Sep 2020 00:00:00 GMT</pubDate>
</item>
```

Is there a possiblity for this to be fixed? It would make it much easier for RSS users such as myself to follow your updates.

Thanks in advance!

**Comment by rubensworks** [comment]
Thanks for reporting! Should be fixed once the CDN updates.
