### ISSUE TITLE
https://comunica.dev/docs/query/getting_started/query_browser_app/ doesn't work

### ISSUE THREAD

**Issue by bjdmeest** [comunica/website#32]
It seems http://rdf.js.org/comunica-browser/versions/2/engines/query-sparql/comunica-browser.js is no longer the right link for the comunica browser build

**Comment by bjdmeest** [comment]
ah, it's a typo! the version should be prepended with a `v`, http://rdf.js.org/comunica-browser/versions/v2/engines/query-sparql/comunica-browser.js resolves

**Comment by rubensworks** [comment]
Thanks for reporting! Could you PR a fix?
