### ISSUE TITLE
The Core Architecture page has some broken link

### ISSUE THREAD

**Issue by constraintAutomaton** [comunica/website#36]
Hi,

The [core architecture page](https://comunica.dev/docs/modify/advanced/architecture_core/) has some broken links. The pages referring to [core classes](https://comunica.github.io/comunica/classes/) does not seem to work.

For example:

- [Actor](https://comunica.github.io/comunica/classes/core.actor.html)
- [Bus](https://comunica.github.io/comunica/classes/core.bus.html) 
- [Mediator](https://comunica.github.io/comunica/classes/core.mediator.html)

The same problem might be also with other pages of the website.

**Comment by rubensworks** [comment]
Oops, those should become case-sensitive, so `https://comunica.github.io/comunica/classes/core.actor.html` should become `https://comunica.github.io/comunica/classes/core.Actor.html`.

Could you submit a pull request to fix the links?

**Comment by constraintAutomaton** [comment]
yes I can
